
export const ADMIN_DB = [
    {
        id: 1,
        imageUrl:'../../assets/img/faces/clem-onojeghuo-3.jpg',
        email: 'asd123@gmail.com',
        userName: 'Umesh',
        password: 'aaaaaa',
        repeatPassword: 'aaaaaa',
    },
    {
        id: 2,
        imageUrl:'../../assets/img/faces/clem-onojeghuo-2.jpg',
        email: 'asd123@gmail.com',
        userName: 'Ganesh',
        password: 'ganuaa',
        repeatPassword: 'ganuaa',
    },

    {
        id: 3,
        imageUrl:'../../assets/img/faces/clem-onojeghuo-3.jpg',
        email: 'asd123@gmail.com',
        userName: 'Jaydeep',
        password: 'japuaa',
        repeatPassword: 'japuaa',
    },
    {
        id: 4,
        imageUrl:'../../assets/img/faces/erik-lucatero-2.jpg',
        email: 'asd123@gmail.com',
        userName: 'Binod',
        password: 'baaaaa',
        repeatPassword: 'baaaaa',
    },
    {
        id: 5,
        imageUrl:'../../assets/img/faces/joe-gardner-2.jpg',
        email: 'manager@gmail.com',
        userName: 'Hari',
        password: 'manager',
        repeatPassword: 'manager',
    },
    {
        id: 6,
        imageUrl:'../../assets/img/faces/kaci-baum-2.jpg',
        email: 'rambo@gmail.com',
        userName: 'Ram',
        password: 'ramboo',
        repeatPassword: 'ramboo',
    },
    {
        id: 7,
        imageUrl:'../../assets/img/faces/kaci-baum-2.jpg',
        email: 'hamro@gmail.com',
        userName: 'Umesh',
        password: '9843223667',
        repeatPassword: '9843223667',
    },
    {
        id: 8,
        imageUrl:'../../assets/img/faces/kaci-baum-2.jpg',
        email: 'ccc@gmail.com',
        userName: 'Umesh',
        password: 'caaaaa',
        repeatPassword: 'aaaaaa',
    },
    {
        id: 9,
        imageUrl:'../../assets/img/faces/kaci-baum-2.jpg',
        email: 'we@gmail.com',
        userName: 'Umesh',
        password: 'wewewe',
        repeatPassword: 'wewewe',
    },
    {
        id: 10,
        imageUrl:'../../assets/img/faces/kaci-baum-2.jpg',
        email: 'user@gmail.com',
        userName: 'Umedsh',
        password: 'userer',
        repeatPassword: 'userer',
    }
];